# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: CC Assets
# All technologies used
technologies: PNG, SVG
# Whether this repository should be featured on the CC Open Source site
featured: false
# Slack channel name
slack: "cc-developers"
